version: "3.4"

services:
  abex:
    build:
      context: .
      target: production
    ports:
      - 6666:6666
    restart: unless-stopped
    stdin_open: true
    env_file:
      - .env.prod
    tty: true
    command: "python command/manage.py runserver 0:6666"
    depends_on:
      - db

  settle-exchange-worker:
    build:
      context: .
      target: production
    restart: unless-stopped
    stdin_open: true
    env_file:
      - .env.prod
    tty: true
    command: "python command/settle_exchange_worker.py"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    env_file:
      - .env.prod
    volumes:
      - abex-mysql-data:/var/lib/mysql/data
    ports:
      - "127.0.0.1:5432:5432"

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      - "DB=postgresql"
      - "DB_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PWD=postgres"
      - "POSTGRES_SEEDS=172.18.0.1"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"

  temporal-web:
    image: temporalio/web:latest
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    ports:
      - "8088:8088"
    depends_on:
      - temporal

volumes:
  abex-mysql-data:
    name: abex-mysql-data