# Generated by Django 5.0.4 on 2024-05-02 15:48

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("IRT", "IRT")],
                        default="USD",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("custom_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
