# Generated by Django 5.0.4 on 2024-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbexSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_amount_intl_exchanges_support",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Minimum amount supported by international exchanges.",
                        max_digits=8,
                    ),
                ),
                (
                    "settle_strategy",
                    models.CharField(
                        choices=[("sync_first", "Sync First"), ("async", "Async")],
                        default="sync_first",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
