# Generated by Django 5.0.4 on 2024-05-03 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cryptocurrency", "0001_initial"),
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "exchange_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        max_length=5,
                    ),
                ),
                (
                    "unit_price_amount",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("IRT", "IRT")],
                        default="USD",
                        max_length=5,
                    ),
                ),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users_exchanges",
                        to="cryptocurrency.cryptocurrency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchanges",
                        to="wallet.wallettransaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExchangeSettlementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("status_code", models.PositiveIntegerField()),
                ("response", models.TextField(null=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_histories",
                        to="exchange.exchange",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
